Repository GauravKarakoti/Omnifood, pull requests merged in 2025-04, with the labels that each got.

#256 CSS Enhanced for Responsiveness, Accessibility, and Maintainability
  public/css/feature_how.css
  public/css/general.css
  public/css/herosection.css
  public/css/navigation.css
  public/css/queries.css
  public/css/testimonials.css
  public/index.html
Labels: bug, enhancement, help wanted, good first issue, medium, apertre2.0

#276 Refactor Duplicate and Redundant DOMContentLoaded Handlers
  public/js/script.js
Labels: easy, apertre2.0

#280 Applied CSRF protection selectively only on routes that render HTML …
  server/index.js
Labels: easy, apertre2.0

#283 Update footer.css
  public/css/footer.css
Labels: enhancement, easy, apertre2.0

#278 Business footer page added
  public/buisness.html
  public/index.html
  public/reciepe.html
Labels: easy, apertre2.0

#289 Fixed Duplicate Server Files Leading to Redundancy
  server.js
  server/index.js
Labels: easy, apertre2.0

#288 Responsive Design, Browser Compatibility, and Code Consistency fixed
  public/about.html
  public/css/CTA.css
  public/css/general.css
  public/css/herosection.css
  public/css/navigation.css
  public/js/script.js
Labels: bug, accessibility, medium, apertre2.0, responsive, css

#300 Update meals.css
  public/css/meals.css
Labels: enhancement, easy, apertre2.0

#284 Made the modification
  public/css/feature_how.css
  public/css/general.css
  public/css/herosection.css
  public/css/meals.css
  public/css/navigation.css
  public/css/pricing.css
  public/index.html
Labels: enhancement, easy, apertre2.0

#302 Enhance navigation styles with hover effects for main navigation links
  public/css/fontqueries.css
  public/css/navigation.css
Labels: bug, easy, apertre2.0

#303 Implemented Font Loading and Fallback Strategies
  public/about.html
  public/buisness.html
  public/carrier.html
  public/cookingpartner.html
  public/css/404.css
  public/css/fontqueries.css
  public/css/general.css
  public/login/style.css
  public/reciepe.html
Labels: easy, apertre2.0

#310 Refactored Duplicate Vendor Prefixes
  public/css/404.css
  public/css/CTA.css
Labels: easy, apertre2.0

#323 solved the cors issue
  public/index.html
  public/js/script.js
  public/login/app.js
  server/index.js
Labels: easy, apertre2.0

#316 Update testimonials.css
  public/css/testimonials.css
Labels: easy, apertre2.0

#306 Conflicting Rules for mobile navigation fixed
  public/css/navigation.css
Labels: easy, apertre2.0

#322 Help Center Page Added
  public/helpcenter.html
  public/index.html
Labels: easy, apertre2.0

#324 Added text alignment on Try for free button
  public/css/navigation.css
Labels: easy, apertre2.0

#325 added become partner form and connected to netlify
  public/cookingpartner.html
Labels: easy, apertre2.0

#326 Update styles for meal cards to improve layout and visual appeal
  public/reciepe.html
Labels: easy, apertre2.0

#332 added favicon
  public/404.html
  public/about.html
  public/buisness.html
  public/carrier.html
  public/cookingpartner.html
  public/helpcenter.html
  public/reciepe.html
Labels: easy, apertre2.0

#335 Changes made
  public/css/general.css
  public/css/navigation.css
  public/index.html
Labels: easy, apertre2.0

#338 Update CTA.css
  public/css/CTA.css
Labels: easy, apertre2.0

#342 Refactor server static file handling and improve code formatting
  server/index.js
Labels: bug, easy, apertre2.0

#344 Update feature_how.css
  public/css/feature_how.css
Labels: easy, apertre2.0

#345 Added search functionality to Recipe Directory
  public/img/seicon.png
  public/img/sicon.jpg
  public/reciepe.html
Labels: medium, apertre2.0

#346 Improve UI for Business Page
  public/buisness.html
Labels: easy, apertre2.0

#347 Improve UI for career page
  public/carrier.html
Labels: easy, apertre2.0

#349 Fix sign-up btn alignment
  public/css/CTA.css
  public/index.html
Labels: easy, apertre2.0

#350 Modified the center help page
  public/helpcenter.html
Labels: easy, apertre2.0

#355 Improve UI for cooking partner and career page
  public/cookingpartner.html
Labels: medium, apertre2.0

#343 Update the button
  public/css/general.css
  public/index.html
Labels: easy, apertre2.0

#362 Adde backend for search functinlaity
  public/index.html
  public/search.html
  server/controllers/hotelController.js
  server/index.js
  server/models/hotelModel.js
  server/package-lock.json
  server/package.json
  server/routes/hotel.js
Labels: hard, apertre2.0

#371 Update buisness.html
  public/buisness.html
Labels: easy, apertre2.0

#372 Update reciepe section
  public/reciepe.html
Labels: easy, apertre2.0

#366 code improvement
  package.json
  public/js/script.js
  public/login/app.js
Labels: medium, apertre2.0

#370 Update about section
  public/about.html
Labels: easy, apertre2.0

#364 Feature/adding oauth authentication
  public/login/login.html
  server/.env.example
  server/index.js
  server/middlewares/passport.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/user.js
Labels: hard, apertre2.0

#373 Update feature_how.css
  public/css/feature_how.css
Labels: easy, apertre2.0

#374 Update general.css
  public/css/general.css
Labels: easy, apertre2.0

#377 Changes the card section
  public/css/navigation.css
  public/css/pricing.css
  public/index.html
Labels: easy, apertre2.0

#380 Enhances the meals section
  public/css/general.css
  public/css/pricing.css
Labels: easy, apertre2.0

#376 Added custom cursor to all the pages
  public/css/404.css
  public/css/general.css
  public/img/cursor.png
  public/login/style.css
Labels: easy, apertre2.0
