Repository GauravKarakoti/Omnifood, pull requests merged in 2025-03, with the labels that each got.

#23 Added issue templates and PR
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: medium, apertre2.0

#31 dynamic year in footer
  index.html
Labels: bug, medium, apertre2.0, seo

#35 dynamic height diff calculator
  css/queries.css
  css/style.css
  js/script.js
Labels: bug, hard, apertre2.0, responsive

#44 Made the modification
  css/queries.css
  css/style.css
Labels: enhancement, easy, apertre2.0

#43 added register pages
  index.html
  js/script.js
  login/app.js
  login/back-icon.png
  login/login.html
  login/logo.png
  login/register.png
  login/style.css
Labels: hard, apertre2.0

#60 Responsiveness of website fixed
  css/queries.css
  css/style.css
  index.html
  js/script.js
Labels: bug, accessibility, medium, apertre2.0, responsive

#61 lazy-loading gallery images
  index.html
Labels: easy, apertre2.0, improvement, performance

#66 Fixes-Navbar with better hover effects.
  css/style.css
Labels: medium, apertre2.0

#69 added 404 page
  404.html
Labels: enhancement, hard, apertre2.0

#71 Gradient Compatibility
  css/queries.css
  css/style.css
Labels: bug, medium, apertre2.0, cross-browser

#72 Fixed SEO, Accessibility, and Usability Issues
  css/general.css
  css/queries.css
  css/style.css
  index.html
  js/script.js
  manifest.webmanifest
  serviceworker.js
Labels: hard, apertre2.0

#77 Fixed: Media Query Breakpoint Ordering Causes Responsive Layout Issues
  css/queries.css
Labels: easy, apertre2.0

#78 Fixed: Missing Image Optimization for Customer Photos and Logo
  img/customers/customer-1.avif
  img/customers/customer-2.avif
  img/customers/customer-3.avif
  img/customers/customer-4.avif
  img/customers/customer-5.avif
  img/customers/customer-6.avif
  img/omnifood-logo.avif
  index.html
Labels: easy, apertre2.0, performance, seo, optimisation

#82 Responsiveness Issue Fixed
  css/general.css
  css/queries.css
  css/style.css
  index.html
  js/script.js
Labels: bug, accessibility, medium, apertre2.0, responsive

#84 Testimonial Section fixed in Mobile Screens
  css/queries.css
Labels: easy, apertre2.0

#88 Best Price Tag fixed and Image in contact form fixed
  css/queries.css
Labels: bug, easy, apertre2.0, responsive

#75 Inaccessible Form Validation and Error Messaging
  css/style.css
  index.html
  js/script.js
Labels: bug, accessibility, medium, apertre2.0, forms

#91 Fixed sticky clsss implementation in Navbar
  css/style.css
  index.html
  js/script.js
Labels: easy, apertre2.0

#96 Twitter icon change
  .gitignore
  css/style.css
  index.html
Labels: easy, apertre2.0

#99 mobile navigation click outside close
  css/queries.css
  css/style.css
  js/script.js
Labels: enhancement, medium, apertre2.0, ux

#95 Fixed: Responsive Design and Media Queries Improvements
  css/queries.css
  css/style.css
  index.html
  js/script.js
Labels: medium, apertre2.0

#105 Adding hover in pricing section
  css/style.css
Labels: enhancement, easy, apertre2.0

#76 CI workflows
  .github/dependabot.yml
  .github/workflows/lighthouse.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  lighthouserc.json
Labels: enhancement, hard, apertre2.0, automation, ci/cd

#113 Redesigned .hero img
  public/img/hero-min.png
  public/img/hero-min.webp
  public/index.html
Labels: enhancement, medium, apertre2.0

#114 Focus Outline Removal
  public/css/style.css
Labels: bug, accessibility, easy, apertre2.0

#128 Updated with hover effects
  public/css/style.css
Labels: easy, apertre2.0

#130 Fix Deprecated Smoothscroll-Polyfill
  public/index.html
Labels: easy, apertre2.0

#131 Mobile Nav Memory Leak
  public/js/script.js
Labels: easy, apertre2.0

#133 Missing Error Handling in API
  server.js
Labels: easy, apertre2.0

#136 Fix/complexity-of-password
  public/login/app.js
  public/login/login.html
  public/login/style.css
Labels: medium, apertre2.0

#137 Page scroll disabled when navbar is open
  public/css/style.css
  public/js/script.js
Labels: easy, apertre2.0

#140 focus styles
  public/css/style.css
Labels: easy, apertre2.0

#139 Feat SEO: Image Optimization
  public/index.html
  public/login/images/back-icon.avif
  public/login/images/back-icon.png
  public/login/images/back-icon.webp
  public/login/images/logo.avif
  public/login/images/logo.png
  public/login/images/logo.webp
  public/login/images/register.avif
  public/login/images/register.png
  public/login/images/register.webp
  public/login/login.html
Labels: easy, apertre2.0

#141 changes
  public/css/style.css
  public/index.html
  public/js/script.js
  server.js
  serviceworker.js
Labels: medium, apertre2.0

#142 Fix Unused CSS Classes
  public/css/general.css
  public/css/queries.css
  public/css/style.css
  public/js/script.js
Labels: easy, apertre2.0

#143 Feature/network based strategy
  public/js/script.js
  serviceworker.js
Labels: easy, apertre2.0

#145 Fix Login Responsiveness for Mobile
  public/login/style.css
Labels: easy, apertre2.0

#146 Gallery Layout Fixed for different screens
  public/css/queries.css
Labels: easy, apertre2.0

#148 404 page implementation
  public/404.html
  public/css/404.css
  public/js/404.js
Labels: medium, apertre2.0

#149 Fixed: Responsive Design - Incomplete Media Queries
  public/css/queries.css
Labels: easy, apertre2.0

#176 Ios hover state persistence
  public/css/style.css
Labels: easy, apertre2.0

#181 Replace Twitter icon with Bootstrap Icons in login.html
  public/login/login.html
Labels: easy, apertre2.0

#177 Font loading strategy
  public/css/style.css
  public/index.html
Labels: easy, apertre2.0

#179 Content Security Policy
  public/css/style.css
  public/index.html
  public/js/script.js
Labels: easy, apertre2.0

#183 Feat/add srcset lazy loading
  public/img/app/app-screen-1.webp
  public/img/app/app-screen-2.webp
  public/img/app/app-screen-3.webp
  public/img/customers/ben.webp
  public/img/customers/dave.webp
  public/img/customers/hannah.webp
  public/img/customers/steve.webp
  public/img/logos/forbes.webp
  public/img/logos/techcrunch.webp
  public/img/logos/the-new-york-times.webp
  public/index.html
Labels: easy, apertre2.0

#186 Add favicon and apple touch icon links to login page
  public/login/login.html
Labels: easy, apertre2.0

#185 Feat/click tracking data
  package-lock.json
  package.json
  public/login/app.js
  server.js
Labels: medium, apertre2.0, performance, database, backend

#188 Add a Search bar & Location
  location-dot-solid.svg
  magnifying-glass-solid.svg
  public/css/style.css
  public/index.html
  public/js/script.js
Labels: enhancement, medium, apertre2.0

#187 Feat/add user page
  public/css/profile.css
  public/js/script.js
  public/login/app.js
  public/profile.html
Labels: hard, apertre2.0

#190 Enhance JWT Authentication Middleware with Better Error Handling and Validation
  server/middlewares/auth.js
Labels: easy, apertre2.0

#192 Update service worker cache version and improve fetch strategy
  serviceworker.js
Labels: easy, apertre2.0

#193 Enhance accessibility of 404 error page by adding ARIA labels to SVG
  public/404.html
Labels: easy, apertre2.0

#194 Feat/add rate limiter
  server/index.js
  server/package-lock.json
  server/package.json
Labels: easy, apertre2.0

#197 Fix css bug
  public/css/style.css
Labels: enhancement, easy, apertre2.0

#198 Implemented csrf protection to login and signup
  package-lock.json
  public/login/app.js
  server/index.js
  server/package-lock.json
  server/package.json
Labels: medium, apertre2.0

#199 Feat/add logout
  public/profile.html
  server/controllers/user.js
  server/routes/user.js
Labels: enhancement, medium, apertre2.0

#201 fix: Clean up CSS specificity issues
  public/css/profile.css
  public/login/style.css
Labels: easy, apertre2.0

#202 Reduce CSS bundle size
  public/css/style.css
  public/index.html
  public/js/script.js
Labels: easy, apertre2.0

#203 Improve form validation feedback
  public/index.html
  public/js/script.js
Labels: easy, apertre2.0

#204 iOS viewport height calculation
  public/js/script.js
Labels: easy, apertre2.0

#205 Improved accessibility in login.html
  public/login/login.html
  public/login/style.css
Labels: easy, apertre2.0

#232 Back to top button in README
  README.md
Labels: doc, apertre2.0

#233 Add JSDoc comments
  public/js/404.js
  public/js/script.js
  public/login/app.js
Labels: doc, apertre2.0

#189 Critical Improvements done - Accessibility, Responsive Behavior, Perf…
  public/css/general.css
  public/css/queries.css
  public/css/style.css
  public/img/hero-min.png
  public/index.html
  public/js/script.js
Labels: hard, apertre2.0

#237 Enhance error messages with ARIA live regions
  public/login/login.html
Labels: easy, apertre2.0

#245 Fix/click tracking
  public/index.html
  server.js
Labels: easy, apertre2.0

#247 New Web Page Added✅
  public/about.html
  public/index.html
Labels: easy, apertre2.0

#252 reafact Change ion icons to bootstrap icons
  public/css/footer.css
  public/css/general.css
  public/css/meals.css
  public/css/pricing.css
  public/index.html
  public/profile.html
Labels: easy, apertre2.0

#253 Feat/register service worker
  public/index.html
  public/js/script.js
Labels: easy, apertre2.0

#254 code splitting
  public/js/routes/about.js
  public/js/routes/contact.js
  public/js/routes/home.js
  public/js/script.js
Labels: easy, apertre2.0

#255 Refactor 404 CSS animations for improved performance
  public/css/404.css
Labels: easy, apertre2.0

#257 Changes in CSS Animation
  public/css/404.css
  public/css/CTA.css
  public/css/addtional.css
  public/css/feature_how.css
  public/css/fontqueries.css
  public/css/footer.css
  public/css/general.css
  public/css/herosection.css
  public/css/location_navbar.css
  public/css/meals.css
  public/css/navigation.css
  public/css/pricing.css
  public/css/profile.css
  public/css/queries.css
  public/css/scrollbtn.css
  public/css/testimonials.css
Labels: medium, apertre2.0

#262 Responsiveness, Accessibility, Duplication, and More
  public/css/scrollbtn.css
  public/index.html
Labels: medium, apertre2.0

#265 Moved the listener registrations outside the click handler and implem…
  public/js/script.js
Labels: easy, apertre2.0

#270 Refactor signup verification token generation to use crypto
  server/controllers/user.js
Labels: easy, apertre2.0
